version: '3.8'
services:
  mysql-db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sm
    ports:
      - "3306:3306"
    networks:
      - springmysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/sm?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    networks:
      - springmysql

networks:
  springmysql:
    name: springmysql